name: Update

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Update dependencies
      run: |
        dotnet remove ./ApplitoolsTutorial/ApplitoolsTutorial.csproj package Eyes.Selenium
        dotnet remove ./ApplitoolsTutorial/ApplitoolsTutorial.csproj package Microsoft.NET.Test.Sdk
        dotnet remove ./ApplitoolsTutorial/ApplitoolsTutorial.csproj package NUnit
        dotnet remove ./ApplitoolsTutorial/ApplitoolsTutorial.csproj package NUnit3TestAdapter
        dotnet add ./ApplitoolsTutorial/ApplitoolsTutorial.csproj package Eyes.Selenium
        dotnet add ./ApplitoolsTutorial/ApplitoolsTutorial.csproj package Microsoft.NET.Test.Sdk
        dotnet add ./ApplitoolsTutorial/ApplitoolsTutorial.csproj package NUnit
        dotnet add ./ApplitoolsTutorial/ApplitoolsTutorial.csproj package NUnit3TestAdapter

    - name: Build
      run: dotnet build 

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'master'  